-- Forge — cloud schema.
--
-- Seven tables, and each one is a thing the app already had a name for. Nothing
-- here is a projection, a cache or a denormalised copy: the phone remains the
-- source of truth, and this is where a practice is kept safe so that losing a
-- phone is not losing a year of mornings.
--
-- Two timestamps on every syncable row, and the difference between them is the
-- whole of the merge design:
--
--   updated_at  written by the device, and it means "when the user changed
--               this". Both sides of a merge compare the same kind of clock.
--   synced_at   written by the server, and it means "when this arrived here".
--               It is the pull cursor, so a device asks for everything newer
--               than the last thing it saw and never has to trust its own
--               clock to page through history.
--
-- Using one column for both is the bug that eats a morning: a device with a
-- slow clock writes a row whose server time is newer than its own, the next
-- pull skips it, and it is never seen again.

-- ---------------------------------------------------------------------------
-- Shared plumbing
-- ---------------------------------------------------------------------------

-- The server stamps its own arrival time on every write. Deliberately not
-- SECURITY DEFINER and deliberately not touching updated_at: what the device
-- said about when the user acted is the device's to say, and overwriting it
-- here would destroy the only ordering the merge can rely on.
create or replace function public.touch_synced_at()
returns trigger
language plpgsql
as $$
begin
  new.synced_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------
--
-- One row per account, holding the settings that shape a morning rather than
-- anything that happened in one. `first_run_completed` is here because it is
-- the one fact that should never be undone by arriving on a new phone.

create table if not exists public.profiles (
    id                   uuid primary key references auth.users on delete cascade,
    day_start_hour       smallint    not null default 4
                             check (day_start_hour between 0 and 23),
    -- 1 = Sunday, matching Calendar.component(.weekday:) on the device.
    rest_weekdays        smallint[]  not null default '{}',
    first_run_completed  boolean     not null default false,
    -- What the on-device classifier has learned from being disagreed with.
    -- Opaque to the server on purpose: it is the user's own vocabulary, and
    -- nothing here has any business reading it.
    verification_memory  jsonb       not null default '{}'::jsonb,
    created_at           timestamptz not null default now(),
    -- Epoch, and not now(). This is the one table whose rows the *server*
    -- creates: the signup trigger below inserts a profile before any device has
    -- said anything, and every column in it is a placeholder rather than a
    -- statement about the user.
    --
    -- Defaulting to now() would date that placeholder later than the real
    -- settings sitting on the phone of somebody who has been using Forge for a
    -- year, so their first sign-in would merge the row in as the winner and
    -- quietly reset the hour their day starts. Dating it from the beginning of
    -- time makes any real client value newer, which is exactly what it is.
    updated_at           timestamptz not null default 'epoch',
    synced_at            timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- devices
-- ---------------------------------------------------------------------------
--
-- What is signed in, so "your practice is on three phones" can be answered
-- honestly. The id is generated by the install and kept in its keychain, which
-- is what makes re-installing on the same phone a new device rather than a
-- silent second identity.

create table if not exists public.devices (
    id             uuid primary key,
    user_id        uuid        not null references auth.users on delete cascade,
    name           text,
    model          text,
    system_version text,
    app_version    text,
    last_seen_at   timestamptz not null default now(),
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now(),
    synced_at      timestamptz not null default now()
);

create index if not exists devices_user_synced_idx
    on public.devices (user_id, synced_at);

-- ---------------------------------------------------------------------------
-- activities
-- ---------------------------------------------------------------------------
--
-- Every activity definition an account owns: the ones somebody invented, and
-- the changes they made to ones Forge ships. Both live here because the app
-- has one edit path for both, and a user renaming something has no reason to
-- care which kind it was.
--
-- `is_deleted` is a tombstone rather than a delete. Without it, throwing an
-- activity away on one phone and syncing from another simply hands it back.

create table if not exists public.activities (
    user_id      uuid        not null references auth.users on delete cascade,
    -- 'custom.<uuid>' for one somebody made, or a library id like 'water'.
    id           text        not null,
    label        text,
    symbol       text,
    goal         text,
    verification text        check (verification in ('health', 'honor')),
    is_custom    boolean     not null default false,
    is_deleted   boolean     not null default false,
    updated_at   timestamptz not null default now(),
    synced_at    timestamptz not null default now(),
    primary key (user_id, id)
);

create index if not exists activities_user_synced_idx
    on public.activities (user_id, synced_at);

-- ---------------------------------------------------------------------------
-- rituals
-- ---------------------------------------------------------------------------
--
-- The arrangement: which activities make up a morning, in which order.
--
-- A table rather than a column on `profiles` because there is exactly one row
-- today ('morning') and there will be more — shared routines are the named
-- next thing, and a routine somebody can send to somebody else has to be a row
-- with an id before it can be anything else. `activity_ids` is an ordered
-- array rather than a join table because the order *is* the data and a join
-- table would need a position column to reconstruct what the array already
-- says.

create table if not exists public.rituals (
    user_id      uuid        not null references auth.users on delete cascade,
    id           text        not null default 'morning',
    name         text        not null default 'Morning',
    activity_ids text[]      not null default '{}',
    updated_at   timestamptz not null default now(),
    synced_at    timestamptz not null default now(),
    primary key (user_id, id)
);

create index if not exists rituals_user_synced_idx
    on public.rituals (user_id, synced_at);

-- ---------------------------------------------------------------------------
-- mornings
-- ---------------------------------------------------------------------------
--
-- What actually happened. The only table anybody would grieve losing.
--
-- `day` is a date and not a timestamp, for the same reason ForgeDay is a civil
-- date on the device: a morning finished in Los Angeles is still Sunday's
-- morning after you land in Tokyo, and re-deriving that from an instant moves
-- it. The label is settled once, on the phone that lived it.

create table if not exists public.mornings (
    user_id      uuid        not null references auth.users on delete cascade,
    day          date        not null,
    -- [{ "ritual_id": "water", "method": "honor", "at": "..." }, ...]
    completions  jsonb       not null default '[]'::jsonb,
    -- What the morning was made of on the day itself, so adding an activity
    -- next week cannot retroactively make last Tuesday incomplete.
    planned_ids  text[]      not null default '{}',
    -- When the blade came free. Null means the morning was not earned.
    extracted_at timestamptz,
    updated_at   timestamptz not null default now(),
    synced_at    timestamptz not null default now(),
    primary key (user_id, day)
);

create index if not exists mornings_user_synced_idx
    on public.mornings (user_id, synced_at);

-- ---------------------------------------------------------------------------
-- blades
-- ---------------------------------------------------------------------------
--
-- Which blade is carried, which have been seen, which have had their moment.
-- Not which are *owned* — that is a reading of how many mornings are in the
-- table above, and storing it would be a second answer that can disagree with
-- its own history.

create table if not exists public.blades (
    user_id          uuid primary key references auth.users on delete cascade,
    equipped_id      smallint    not null default 1,
    acknowledged_ids smallint[]  not null default '{}',
    celebrated_ids   smallint[]  not null default '{}',
    updated_at       timestamptz not null default now(),
    synced_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- premium_status
-- ---------------------------------------------------------------------------
--
-- A record of what the App Store told a device, and nothing more.
--
-- This row does not grant anything. The device reads its entitlement from
-- StoreKit, which is signed by Apple and already follows an Apple Account
-- across phones; a row a client can write is not evidence of a purchase, and
-- treating it as one would mean the entitlement could be granted by anybody
-- who can send an HTTP request. It is here so support can answer "what does
-- this account think it has" and so a future server-side check has somewhere
-- to write its answer.

create table if not exists public.premium_status (
    user_id     uuid primary key references auth.users on delete cascade,
    entitlement text        not null default 'free'
                    check (entitlement in ('free', 'subscribed', 'lifetime')),
    product_id  text,
    updated_at  timestamptz not null default now(),
    synced_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- synced_at triggers
-- ---------------------------------------------------------------------------

do $$
declare
    t text;
begin
    foreach t in array array[
        'profiles', 'devices', 'activities', 'rituals',
        'mornings', 'blades', 'premium_status'
    ] loop
        execute format(
            'drop trigger if exists %I on public.%I', t || '_touch_synced_at', t
        );
        execute format(
            'create trigger %I before insert or update on public.%I
             for each row execute function public.touch_synced_at()',
            t || '_touch_synced_at', t
        );
    end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
--
-- On for every table, with no exceptions and no service-role shortcut in the
-- app. Two halves to each policy and both matter:
--
--   using       what an existing row must satisfy to be seen or changed
--   with check  what a row must satisfy *after* the write
--
-- The second is what makes a client-supplied user_id worthless. A device can
-- put any uuid it likes in the column; the insert is refused unless that uuid
-- is the one in its own JWT. Nothing in the app ever sends a user id that the
-- server then trusts — auth.uid() is read from the signed token, every time.

alter table public.profiles       enable row level security;
alter table public.devices        enable row level security;
alter table public.activities     enable row level security;
alter table public.rituals        enable row level security;
alter table public.mornings       enable row level security;
alter table public.blades         enable row level security;
alter table public.premium_status enable row level security;

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------
--
-- Spelled out rather than left to whatever default privileges happen to be in
-- effect. RLS decides *which rows* a role may touch; the grant decides whether
-- it may touch the table at all, and the two failures look nothing alike: a
-- missing policy returns an empty list, a missing grant returns 42501 and the
-- app maps it to `.forbidden`, which is deliberately not retryable. That would
-- be a sync that never works and never tries again.
--
-- `anon` is revoked explicitly. It is very likely already true, and it is the
-- single most important sentence in this file: an unauthenticated request must
-- reach no row of any table. It is also what makes anonymous use of Forge free
-- to run — it never gets here at all.

do $$
declare
    t text;
begin
    foreach t in array array[
        'profiles', 'devices', 'activities', 'rituals',
        'mornings', 'blades', 'premium_status'
    ] loop
        execute format(
            'grant select, insert, update, delete on public.%I to authenticated', t
        );
        -- service_role as well. It is not used by the app and never will be,
        -- but it is what the Dashboard's table editor, the admin API and any
        -- future Edge Function run as — and a table it cannot read is one
        -- nobody can support a user through.
        execute format('grant all on public.%I to service_role', t);
        execute format('revoke all on public.%I from anon', t);
    end loop;
end;
$$;

grant usage on schema public to authenticated, service_role;

drop policy if exists "profiles are their owner's" on public.profiles;
create policy "profiles are their owner's"
    on public.profiles for all to authenticated
    using (auth.uid() = id)
    with check (auth.uid() = id);

do $$
declare
    t text;
begin
    foreach t in array array[
        'devices', 'activities', 'rituals', 'mornings', 'blades', 'premium_status'
    ] loop
        execute format('drop policy if exists %I on public.%I', t || ' are their owner''s', t);
        execute format(
            'create policy %I on public.%I for all to authenticated
             using (auth.uid() = user_id)
             with check (auth.uid() = user_id)',
            t || ' are their owner''s', t
        );
    end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Profile on signup
-- ---------------------------------------------------------------------------
--
-- Created by the database rather than by the app. A device that signs in and
-- then loses the network before its first write would otherwise have an
-- account with nothing behind it, and the next sign-in would have no way to
-- tell that from a fresh one.
--
-- `on conflict do nothing`: this runs once per user by construction, but a
-- retried signup must not be an error, and the client's own profile upsert
-- must not race it into a duplicate.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id) values (new.id)
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();
